### ISSUE TITLE
LOAD raw mode always returns SUCCESS when loading in raw mode

### ISSUE THREAD

**Issue by ki-bo** [MEGA65/mega65-rom-public#125]
**Test Environment (required)**
You can use [MEGA65INFO](https://files.mega65.org?id=3eeb7d82-8bd7-44b7-82b6-cef29d123b0e) to retrieve this.
 - Platform: MEGA65R3a
 - ROM Release: 920395
 - Core Commit: 0.96

**Describe the bug**
When loading a file in raw mode (bit6 of A is set when calling LOAD at $ffd5), then the error reporting is broken. If the file could not be loaded, it is expected that C is clear, but it is set in any case.

**To Reproduce**
1. Use this program to load a non-existent file "TEST":
```
	lda #$04
	ldx #<filename
	ldy #>filename
	jsr $ffbd		// SETNAM
	lda #$00
	ldx #$08
	ldy #$00
	jsr $ffba		// SETLFS
	lda #$00
	ldx #$00
	jsr $ff6b		// SETBNK
	lda #$40		// bit6=1 is RAW mode, don't skip first two bytes
	ldx #$01
	ldy #$50
	jsr $ffd5		// LOAD

	bcc loadok
	lda #2
	sta $d020
	jmp *
loadok:
	inc $d020
	jmp loadok


filename:
	.text "TEST"
```
2. Execute and make sure the file TEST is not on the mounted disk image or floppy disk
3. The border will cycle colours as if the LOAD succeeded

**Expected behavior**
Border should turn red to indicate a LOAD error (carry set when routine returns)

**Additional context**
If changing A to 0 again before calling $FFD5, everything works as expected.
I believe that raw mode is a new feature introduced by the MEGA65 ROM, and probably was not there with C65, as it is not documented. I only learned about it on Discord.

**Comment by dansanderson** [comment]
As it is currently written, it's relying on reading the first two bytes to detect File Not Found, and in fact any issue with reading the first two bytes will be reported as File Not Found. In raw mode, it doesn't read any bytes before proceeding as if the file exists.

We might be able to rewrite this to always read the first two bytes into a temporary spot, FNF on any error (not perfect but probably ok), then write those two bytes to the requested memory address if in raw mode and proceed from start+2. Alas, more design flaw than bug, but still fixable.

**Comment by dansanderson** [comment]
oof, lots of edge cases here, would need a major rewrite to do it that way. backing away from that idea.

Strange because subsequent reading of the non-existent file should also error. The "timeout" call path does set Carry. Somehow this is exiting by another path in this case.

**Comment by dansanderson** [comment]
... When this load happens from an internal disk, it uses CBDOS FastLoad, which does not appear to detect or report errors. It just assumes that previously run code verified that the file exists, and makes no attempt that I can see to report failure to the caller.

As far as I can tell, a non-existent file has the same result as a zero-byte file in this call path. Maybe on `load_done` we can detect a zero byte file (eal=sal), then in that case try another disk operation to confirm that the file exists and report FNF if it doesn't. That's rare enough that another disk op to confirm wouldn't be burdensome.

Gonna pause this for now. Hopefully this isn't too intrusive in the meantime.

**Comment by ki-bo** [comment]
As the load without the RAW bit (6) set is reporting an error, I think it should be implemented for load somewhere. It just is not working in that mode. Can we still fix this?

**Comment by dansanderson** [comment]
It's fixable, I only paused this because it was going to be more than a few lines to change.

To summarize: Load without RAW is detecting File Not Found by attempting to load the address bytes and checking the drive for an error status. RAW mode is skipping that check and proceeding directly to loading the file. For the virtual disk, the rest of the code path doesn't test for or report errors (as far as I can tell).

* If RAW for IEC devices is reporting errors correctly and only virtual disks are affected, then one fix is to get the virtual disk code path to report errors.
* If RAW for IEC isn't reporting errors either, and somehow the address read is detecting the error, then one possible fix is to rewrite this code to read one byte for error checking and proceed to use that byte as either the first address byte or the first data byte. As above, I tried this and noticed it would be a major rewrite.

A small-change hack would be for both non-RAW and RAW to attempt to read the address bytes, and for RAW to close and re-open the channel before reading to reset the position of the next read. This would slow down a RAW load a bit, and would fail on one-byte RAW files.

**Comment by dansanderson** [comment]
OK I think I see how I can read two bytes, then write those two bytes to memory in RAW mode. This would require that a file loaded with RAW be at least two bytes in size.

This could be made more complex to read just one byte for the FNF check. This still wouldn't support RAW mode files of zero bytes, which presumably should succeed and return the starting address.

Considering RAW mode is a new MEGA65 feature, we could make it a requirement that RAW files contain at least two bytes.

**Comment by dansanderson** [comment]
This is now fixed. The fix requires that a PRG file loaded in raw mode contain at least two bytes.
