### ISSUE TITLE
"Highlighting" of disk errors is inconsistent, doesn't always reset properly

### ISSUE THREAD

**Issue by dansanderson** [MEGA65/mega65-rom-public#153]
**Test Environment (required)**
 - ROM Release: 920407, but has been noticed for many versions

**Describe the bug**
BASIC tries to print disk errors after disk commands in the "highlight" color, but it sometimes fails to do so, and sometimes succeeds but then fails to reset the color back. I'm unsure of the exact circumstances, but at least half of that can be reproduced after a cold boot, e.g. type `BOOT` with nothing mounted.

![mega65-screen-000002](https://github.com/user-attachments/assets/a02f6cd5-8021-4471-9e82-1b0f39936562)

Look for `highlight` in b65.src, possibly one of the uses of `highlight_text` and `highlight_done` (i.e. the first getting called without the second).

**Comment by Rhialto** [comment]
The weird thjng is, I could reproduce it over several resets and ROM changes, but now I did a power cycle and I could no longer reproduce it....
The reason for the power cycle was that the "syntax colouring" of the basic LIST command stopped working. And M65Connect didn't download d81 images any more. These things sound like they should have nothing to do with each other, and I power-cycled to get a hopefully clean slate.

**Comment by snoopy-f64** [comment]
I've just tried it at least 30 times in different constellations. I have not been able to reproduce this bug on the current Xemu with ROM 920407. This color error does not occur in the emulator.

**Comment by Rhialto** [comment]
It seems like the error has something to do with `fndcnt`. At least, if you  `POKE $2D2,1`, you get into the state I found: 1 disk error gets in highlighted colour. If you reset the colour and do it again, no highlight color. LISTing a program doesn't highlight the basic tokens either.
Once you `POKE $2D2,0` again, the situation is still not quite back to normal: the first LIST still doesn't colour right. But the second one does. That is probably because it needs to go through another "highlight / back to normal" cycle to be really normal again.
Once `findcnt` got set in my case (if that was actually it), there isn't really anything that resets it. There seems to be only a `dec fincnt` in `highlight_find`, and it is called from various places (not just FIND), it tests if "FIND active?" and does nothing if not.
I didn't analyze those "various places" yet, but effectively some of them might be unnneeded. 
So if in my original case it was some program which wrongly wrote to the wrong memory (`fincnt` in this case), it isn't really a BASIC bug. On the other hand it could be made more resilient anyway, by resetting it at some opportune location. At least when a RESET happens (or every READY prompt, or ...)

If somehow the ROM code manages to leave `fincnt` set all by itself, then of course that should be fixed. But so far I am not convinced that that is the case.

![screenshot-20240804-145649](https://github.com/user-attachments/assets/683a3c0c-0266-4d4c-8108-8ebf06e24c1a)

**Comment by Rhialto** [comment]
The interacting of highlighting from FIND and the normal one from LIST (highlighting the basic keywords) isn't great. The output from FIND loses the latter. And if the same pattern is found multiple times in the same line, the line is re-listed for every match. Some overhaul could surely improve things, and hopefully it could make the interactions of the highlights less fragile.
There may be more things in the ROM that depend on initial memory values. I don't know if there is space in the FPGA to add an extra bit to every byte to track if it has been initialized? Otherwise Xemu could do such a thing perhaps.

**Comment by lgblgblgb** [comment]
Btw, I tried to hack in for myself what @Rhialto suggested in https://github.com/lgblgblgb/xemu/issues/405 my result after trying to use `BOOT`:

```
MEM: main RAM at linear address $200 has been read without prior write at PC=$229F
MEM: main RAM at linear address $200 has been read without prior write at PC=$229F
MEM: main RAM at linear address $202 has been read without prior write at PC=$229F
MEM: main RAM at linear address $200 has been read without prior write at PC=$229F
MEM: main RAM at linear address $201 has been read without prior write at PC=$2296
MEM: main RAM at linear address $202 has been read without prior write at PC=$229F
MEM: main RAM at linear address $202 has been read without prior write at PC=$229F
MEM: main RAM at linear address $101A0 has been read without prior write at PC=$8613
MEM: main RAM at linear address $101A0 has been read without prior write at PC=$8613
MEM: main RAM at linear address $101A0 has been read without prior write at PC=$8613
```

It was with ROM `V920400`. The actual PC values can be off by some bytes, because of the opcode execution emulation (ie, PC is already incremented and does not point to the actual opcode byte). I have some hope that this information can be useful for @dansanderson (or for others too).

**Comment by Rhialto** [comment]
@lgblgblgb Interesting! $200 is the input buffer and $229F (I looked in a slightly later version of the ROM, so addresses would differ a bit more) is chrget/chrgot, i.e. reading from the input buffer.
I was really expecting to see $2D2 in the list. I wonder how it managed to escape. You can easily verify that it keeps its value over a RESET. Also it affects error messages and LIST output. So I definitely expected to see it with this hack.

**Comment by lgblgblgb** [comment]
@Rhialto Dunno about $2D2, now I've put some extra debug stuff, and nothing ever writes/reads that memory address, at least from "cold boot" to the point that I do `DIR`, `BOOT` and stop the debugging then. It shows up though after doing `BANK 0 : ?PEEK($2D2)` so the monitoring of uninited read should be working. I also checked the full output (ie from startup to exit of Xemu), what I included here is just the part was done during `BOOT`.

By the way, ROM `V920407` with some fancy stuff added (decoding the linear address belonging the PC values):

```
MEM: DEBUG: main RAM at linear address $200 has been read without prior write; PC=$229F [$3229F]
MEM: DEBUG: main RAM at linear address $200 has been read without prior write; PC=$229F [$3229F]
MEM: DEBUG: main RAM at linear address $202 has been read without prior write; PC=$229F [$3229F]
MEM: DEBUG: main RAM at linear address $200 has been read without prior write; PC=$229F [$3229F]
MEM: DEBUG: main RAM at linear address $201 has been read without prior write; PC=$2296 [$32296]
MEM: DEBUG: main RAM at linear address $202 has been read without prior write; PC=$229F [$3229F]
MEM: DEBUG: main RAM at linear address $202 has been read without prior write; PC=$229F [$3229F]
MEM: DEBUG: main RAM at linear address $101A0 has been read without prior write; PC=$8613 [$20613]
MEM: DEBUG: main RAM at linear address $101A0 has been read without prior write; PC=$8613 [$20613]
MEM: DEBUG: main RAM at linear address $101A0 has been read without prior write; PC=$8613 [$20613]
```

**Comment by Rhialto** [comment]
Ok, and if you do `BOOT` right after a reset, on a disk without the boot file, so that it prints an error. Then I would expect this to be the first read: `3f88 ad d2 02     lda fincnt` in `highlight_done`. At that point it decides *not* to end the highlight, if the value is not 0.

**Comment by lgblgblgb** [comment]
> Ok, and if you do `BOOT` right after a reset, on a disk without the boot file, so that it prints an error. Then I would expect this to be the first read: `3f88 ad d2 02 lda fincnt` in `highlight_done`. At that point it decides _not_ to end the highlight, if the value is not 0.

The odd thing that while I tried `BOOT` there is no read, neither write operation to $2D2 (I mean any operation, not just "uninited" kind of read - also with the full boot flow included), I added some extra debugging. Still the red-coloured error is shown. Sure, I cannot be 100% sure that I haven't done something stupid, so that's the reason I haven't seen that.

**Comment by dansanderson** [comment]
The next time someone sees this, can you please `?PEEK($02A6),PEEK($02D2)` and post the result? I haven't been able to reproduce this recently using the proposed procedures (auto-mount valid image without auto-boot then `BOOT` = File Not Found, or set auto-mount to invalid image then `BOOT` = Device Not Ready).

$02A6 is `savcolor`, which uses bit 7 to lock the value to prevent highlighting from being re-entrant and spoiling the restore color. If bit 7 is set, the contents are considered "invalid" and `highlight_done` will make no changes. From code review, only `highlight_a` and `highlight_done` mess with this and they appear to do so consistently. I don't know if something else is messing with it.

@lgblgblgb KERNAL variable $00F1 is the cursor color itself. If there's anyone changing this without going through the highlight mechanism (like any other text color change), it could not be getting restored. It might be interesting to Xemu-watch $00F1, if this case can be reproduced. (Note that all cursor color changes touch this, including PETSCII codes and the FOREGROUND command, so that's not unusual.)

**Comment by Rhialto** [comment]
Interesting, `[$24E51]` is, according to b65alt.lst, in the GO 65 routine. It's put in ROM as a hex dump, not source, so it's not so easy to see what's happening there.

**Comment by dansanderson** [comment]
@Rhialto Yup, we obscure the Easter egg for an undisclosed reason. Unfortunately we've also lost the original secret source. 😅

**Comment by dansanderson** [comment]
... oh I should also mention, if you're looking at b65alt.lst for troubleshooting this issue, keep in mind that ROMalt uses a different memory map, so those addresses don't line up or apply to the regular ROM mode. Currently, ROMalt is only used for the bitplane graphics subsystem and GO 65.

**Comment by Rhialto** [comment]
I just tried if location `$2D2` gets preserved over a RESET in xemu-xmega65, and there it doesn't. "Reset CPU only" does preserve the memory (and also re-starts BASIC). Maybe that makes a difference in read-before-write detection?

**Comment by lgblgblgb** [comment]
```
MEM: DEBUG: main RAM at linear address $F1 has been WRITTEN with value $01; PC=$E6A3 [$3E6A3]
MEM: DEBUG: main RAM at linear address $101A0 has been read without prior write; PC=$8613 [$20613]
MEM: DEBUG: main RAM at linear address $101A0 has been read without prior write; PC=$8613 [$20613]
MEM: DEBUG: main RAM at linear address $101A0 has been read without prior write; PC=$8613 [$20613]
MEM: DEBUG: main RAM at linear address $F1 has been WRITTEN with value $01; PC=$E6A3 [$3E6A3]
MEM: DEBUG: main RAM at linear address $F1 has been WRITTEN with value $08; PC=$3FAC [$33FAC]
MEM: DEBUG: main RAM at linear address $F1 has been WRITTEN with value $01; PC=$3F94 [$33F94]
MEM: DEBUG: main RAM at linear address $F1 has been WRITTEN with value $01; PC=$E6A3 [$3E6A3]
MEM: DEBUG: main RAM at linear address $F1 has been WRITTEN with value $01; PC=$E6A3 [$3E6A3]
MEM: DEBUG: main RAM at linear address $F1 has been WRITTEN with value $01; PC=$E6A3 [$3E6A3]
```

**Comment by dansanderson** [comment]
@Rhialto ooh, nice theory! From code, `fincnt` is only ever set by `print_line`, so if something goes through the `highlight_*` code path a different way without initializing `fincnt` correctly, that could be an issue. If it's a disk error during the boot state, then an error might get printed by other means before the first `print_line` call, then the issue is up to whatever happens to be in memory.

If so, the fix is probably to zero `fincnt` in `init_sound_sprites`, which is where `helper` and `savcolor` are initialized.

Do we have a repeatable repro procedure, at least on one of our machines? I can implement this change and send a test ROM, if I can't get it repro'd on my end.

**Comment by Rhialto** [comment]
As far as I could see, `print_line` is even only used by the FIND command. So it's really easy that a highlight gets triggered by something else: the infamous disk error, LIST printing a keyword, maybe more things.

**Comment by dansanderson** [comment]
The initialization hypothesis is supported by the observation that it's mostly happening when printing a highlighted message (esp. disk status) during or just after boot. That's where I've seen it too, I think especially after doing an Intro Disk run-through.

Warm booting after any program that takes over $0200... and leaves a non-zero value in $02D2 will cause the sticky orange on next disk error:

1. Cold boot.
2. Attempt to load a non-existent file: `DLOAD "XXX"` Prints orange error, white Ready prompt.
3. `POKE $2D2,1`
4. Attempt to load a non-existent file: `DLOAD "XXX"` Prints orange error and orange Ready prompt, leaves cursor orange.
5. Warm boot: press Reset button.
6. Attempt to load a non-existent file: `DLOAD "XXX"` Prints orange error and orange Ready prompt, leaves cursor orange.

I'm confident enough this is the fix that I'm going to resolve the issue. Please reopen if you see it again after this fix is released (or test with your own ROM build).

Thanks for the help!
