### ISSUE TITLE
FIND can not find line with REM command

### ISSUE THREAD

**Issue by snoopy-f64** [MEGA65/mega65-rom-public#17]
**Test Environment (required)**
 - Platform: xmega65
 - ROM Release: 920371

**Describe the bug**
It's not possible to find lines with REM with the FIND command

**Screenshots**

![mega65_find_a](https://user-images.githubusercontent.com/66867430/175057363-a81caf8f-d217-4523-882b-d5e15fc299a2.png)

**Comment by dansanderson** [comment]
REM is pre-processed out of the text before the command is tokenized, so `FIND /REM/` looks like `FIND /`. It might be a substantial change to support this edge case. `FIND` relies on the line tokenizer for non-quoted patterns, so to preserve `REM` in such a pattern would require major changes to line handling (such as a special `FIND` parsing mode in `crunch`, `find_bend` or both).

**Comment by dansanderson** [comment]
I'm resolving this as will not fix, because the size of the code change does not justify supporting the edge case. FIND can search the text of remarks with a double-quoted search term, it just can't see the REM keyword when using a slashed search term.

I have added a note about this to the documentation for FIND.

**Comment by snoopy-f64** [comment]
I just found a solution for this issue: It's an issue in the documentation. ;-)

Instead of using slashs for FIND you have to use **colons**. Then the lines with REMs will be found.

![find_a](https://github.com/MEGA65/mega65-rom-public/assets/66867430/7e128374-02eb-4fa2-a88e-1947d77e3fb6)

It will works also with DATA, which has the same issue as REM:

![find_b](https://github.com/MEGA65/mega65-rom-public/assets/66867430/cf28cdcc-521a-418f-b9eb-cfb13d231dfa)

**Comment by dansanderson** [comment]
wow, nice! That works well. The implementation says the delimiter can be any character, so it's just the documentation suggesting the use of the slash. As far as I can tell, recommending the colon as the non-double-quote delimiter by default covers all of the cases. Let me know if you find any issue with just recommending the colon, otherwise I'll just update the docs that way.

Nice work! :)

**Comment by dansanderson** [comment]
... I notice that this isn't as successful with `CHANGE`.

```
CHANGE :FOO: TO :BAR:
```

is a syntax error.
```

**Comment by dansanderson** [comment]
Added a note to FIND: https://github.com/MEGA65/mega65-user-guide/blob/4a5030b9184775345612f2f10f50d0abc05d70da/appendix-basic65.tex#L4191

Added a note to CHANGE: https://github.com/MEGA65/mega65-user-guide/blob/4a5030b9184775345612f2f10f50d0abc05d70da/appendix-basic65.tex#L1550
