### ISSUE TITLE
Weird behaviour using the CURSOR ON command

### ISSUE THREAD

**Issue by jwa1974** [MEGA65/mega65-rom-public#175]
**Test Environment (required)**
You can use [MEGA65INFO](https://files.mega65.org?id=3eeb7d82-8bd7-44b7-82b6-cef29d123b0e) to retrieve this.
 - Platform: MEGA65 R6
 - ROM Release: 920395 / 920408
 - Core Commit: 3c10488

**Describe the bug**
When using the ON setting with CURSOR, the cursor will leave garbage when "moving" around.

**To Reproduce**

First use case - setting ON;
1. Enter the example program in the User's Guide under `CURSOR` (see under additional context).
2. Change line 20 to `CURSOR ON,1,2`.
3. Run.
4. The cursor will "stick" on some positions, as seen in the first screenshot.

Second use case - setting ON and no SCNCLR;
1. Enter the example program in the User's Guide under `CURSOR` (see under additional context).
2. Disable the `SCNCLR` on line 10, e.g. `REM SCNCLR`.
3. Change line 20 to `CURSOR ON,1,2`.
4. Place a `?` after each of the printouts from the last run.
5. Run.
6. The cursor will reverse the `?` on some positions. It will also place a `?` at the READY prompt. An additional `C` will overwrite the `?` placed after `ABC`. The second screenshot illustrates this.

**Expected behavior**
No garbage should be left by the CURSOR command when using ON. When setting is OFF, no garbage seems to be left.

**Screenshots**
Screenshot 1:
![problem 1](https://github.com/user-attachments/assets/92ae59c6-110b-41aa-a610-438368a26400)

Screenshot 2:
![problem2](https://github.com/user-attachments/assets/06142b3e-cd86-43c7-9241-7213e203b47d)

**Additional context**
The program in the User's Guide:

```
10 SCNCLR
20 CURSOR 1,2
30 PRINT "A"; : SLEEP 1
40 PRINT "B"; : SLEEP 1
50 PRINT "C"; : SLEEP 1
60 CURSOR 20,10
70 PRINT "D"; : SLEEP 1
80 CURSOR ,5 : REM MOVE THE CURSOR TO ROW 5 BUT DO NOT CHANGE THE COLUMN
90 PRINT "E"; : SLEEP 1
100 CURSOR 0 : REM MOVE THE CURSOR TO THE START OF THE ROW
110 PRINT "F"; : SLEEP 1
```

**Comment by dansanderson** [comment]
Good find! I think the general explanation is that if the cursor is ON, the cursor is relocated with another CURSOR command, and the blink state happens to be on when this happens, then it neglects to clear the cursor blink state. I'd be curious if other ways of relocating the cursor also have this issue or if it's just the CURSOR command that needs additional logic to clear the blink state. (PRINT probably does the right thing, but it's worth testing.)

**Comment by jwa1974** [comment]
I did another test according to your suggestion, Dan. So, instead of moving with the CURSOR command, I only enabled the cursor and then "moved around" with regular PRINTs.

Still same issue. I include a screenshot of the first run, just to show the issue still remains - and the code I did the test with.

![print_moves](https://github.com/user-attachments/assets/b4664a06-2939-4c1f-85a3-0680f1eb52b0)

**Comment by Rhialto** [comment]
I think the ROM makes the reasonable assumption that the cursor is OFF, unless it is in the BASIN input loop at `waitky`. In there it turns off the cursor by `jsr crsroff`. Doing that for every character that is printed to the screen seems like it would seriously slow it down...

**Comment by dansanderson** [comment]
Stashing the cursor mode and disabling the cursor before moving the cursor, then restoring it after, with CURSOR works well.

I tried to refactor PRINT slightly to use a similar technique and ran into minor catastrophe. For now, we can document that a BASIC program that uses CURSOR ON must be diligent about turning it off before doing other things on the screen. We can keep the fix for relocating with CURSOR as a convenience.

I realize this is an incomplete solve for what I assume are most use cases for CURSOR ON, e.g. turn on the cursor, wait for chars with GETKEY, then PRINT those chars. With only a partial fix, such a program would have to be mindful to disable the cursor when encountering a cursor-moving PETSCII code. Maybe `CURSOR ON : GETKEY A$ : CURSOR OFF : PRINT A$` ought to be the intended API for this (obviating the need for the partial fix in these cases). I will add this to the docs on CURSOR.
