### ISSUE TITLE
RENUMBER removing whitespace after THEN

### ISSUE THREAD

**Issue by rscottfree** [MEGA65/mega65-rom-public#18]
**Test Environment (required)**
 - Platform: MEGA65
 - ROM Release: 920376
 - Core Commit: 80fc1c0

**Describe the bug**
Renumbering a basic program with `THEN` keyword will remove any whitespace that comes after `THEN`.

**To Reproduce**
1. Create a basic program like this:
> 10 IF I=0 THEN PRINT "HI"

3. Then run `RENUMBER10,10`
4. List the program and you'll see the removed whitespace between `THEN` AND `PRINT`.
> 10 IF I=0 THENPRINT "HI"

**Expected behavior**
It would be nice if the whitespace were preserved as it appears to be for other keywords

**Additional context**
It behaves the same whether it's a logical or numeric expression after the `THEN` keyword. I consider this low priority but wanted to document it.

**Comment by dansanderson** [comment]
So, you're not going to believe this, but this is an undocumented "feature" of RENUMBER. If you omit the space between `RENUMBER` and its first argument, it will omit the whitespace that precedes line numbers in the translated source.

🤯

Try `RENUMBER 10,10` in the example above and it'll preserve the whitespace. Note that if the source started out with no space before the line number, it'll stay that way in either case.

I don't know what to say about this dubious feature, but it's clearly intentional from the code, so not really a bug. If anyone wants me to remove it such that whitespace is preserved regardless of invocation, please reopen the ticket and I'll gladly do so. 😄

**Comment by dansanderson** [comment]
— Actually I'm going to remove it. I just noticed that your example shows it is crunching whitespace after tokens that may or may not be followed by line numbers. This is a useless feature with unintended side effects.
