### ISSUE TITLE
brk should be two bytes?

### ISSUE THREAD

**Issue by dansanderson** [MEGA65/mega65-rom-public#20]
**Test Environment (required)**
- Platform: MEGA65
- ROM Release: 920376
- Core Commit: f55531

**Describe the bug**
By historical accident of implementation, and despite what datasheets say, the 6502 BRK instruction is treated as two bytes: the PC that gets pushed to the stack by BRK is the address of the BRK instruction plus 2.

* See the MEGA65 Book, Appendix H: 45GS02 & 6502 Instruction Sets
* [What are uses of the byte after BRK instruction on 6502?](https://retrocomputing.stackexchange.com/questions/12291/what-are-uses-of-the-byte-after-brk-instruction-on-6502)
* [Internals of BRK/IRQ/NMI/RESET on a MOS 6502](https://www.pagetable.com/?p=410)
* [That BRK instruction...](http://forum.6502.org/viewtopic.php?f=2&t=1917&sid=8e106a233329de16dd1e43387696b958)

I can't quite tell experimentally what the 45GS02 does when it encounters a BRK. It appears that certain parts of the ROM treat BRK as one byte. When I use BRK to enter BS Monitor, the PC appears as the address of BRK plus one. BS Monitor also assembles BRK to one byte.

I can say that ACME assembler assembles BRK to one byte, so any inconsistent handling may need to take third-party tools into account.

```
!cpu m65
*=$3000

brk
inc $d020
brk
```

assembles to:

```
00 ee 20 d0 00
```

I have not yet experienced a bug related to incorrect brk handling. I'm raising this because modern docs all warn about BRK being two bytes, but this toolchain seems to treat it as one. There appears to be no agreement on *how* the second byte should be assembled, and there is no conventional way to distinguish between a one-byte BRK and a two-byte BRK emitted from a tool.

We should review the parts of the core and ROM involved in BRK handling, and confirm with the major assemblers that BRK is handled correctly and consistently by the core, assemblers, and BS Monitor. We should decide on a convention, a support strategy, and (if necessary) a migration strategy.

There may not be a perfect solution. For example, maybe we limit support for two-byte BRK to cases where both bytes are 0: if a BRK is followed by a 0, increment the PC by 2, otherwise increment the PC by 1.

**Comment by dansanderson** [comment]
fwiw I would be satisfied with the answer, "The combination of the CPU and the brk handler always end up setting the return address to the byte after the brk instruction, and assemblers always assemble brk to one byte." I want to know if that's the actual answer, given the contradictory documentation about the expected behavior of the CPU in isolation.

**Comment by dansanderson** [comment]
I still haven't figured out how to reconcile the "brk is two bytes" lore with the behavior of CPUs, assemblers, and monitors, but it doesn't appear to be a problem with the implementation, so I'll close this. I do wonder if we should make the assembly language reference paragraph on this topic a bit more complete by explaining why everything treats brk as one byte, but that's a doc issue, and a minor one. Closing.

**Comment by lgblgblgb** [comment]
@dansanderson I see you've closed this already, however if it helps at all, my view on this:

BRK is one byte opcode as the CPU needs one byte to interpret the "what to do" stuff. It's totally different thing what pushed onto the stack. It's kind of like JSR/RST stuff which is "off by one" compared to other CPUs! But again, that's true that returning from the BRK handler, indeed, you're one byte further "as should be". So the BRK handler itself may pop the return address from the stack, decrement it, and pushes back, so the return address will be OK. I think this is what the answer means with "CPU and brk handler always ends up" ... with some custom routine in the BRK handler to "fix" this. Not so much relevant here, but this feature actually can be used to have BRK + parameter passed as well ;) I doubt it was ever used that way on C65, I used as a "SYSCALL" opcode in my old "C64 OS" though, to have a SYSCALL number passed, by adding a byte after BRK though (then for sure you don't even need to "patch" the return address in the stack).

Btw, this reminds me the other myth (though not this topic from now!), that there is a B "true bit" in the flags register, which is not ;) For real there is no B flag at all. All the important part, that every "software cause" pushes flags into stack pushes the "virtual" B flag as being set (that is: BRK and PHP), and every "hardware cause" (IRQ, NMI) pushes as not set, that's simple. It's not kept in the CPU flags register at all, that bit is simply not used. That's also a reason you can't PLP something to set/reset B flag since there is not even such a thing.

**Comment by dansanderson** [comment]
@lgblgblgb Thanks for the reply! It sounds like this is important information for anyone hard-wiring a custom IRQ handler directly to FFFE-FFFF that might need to handle a BRK. The ROM soft IRQ vectors presumably already handle this, and the Monitor ought to assume that BRK is always intended as one byte and the return address ought to be adjusted appropriately. Anyone doing anything fancy with the "second" BRK byte needs to account for it themselves.
