### ISSUE TITLE
Make PLAY command robust against sending new sequence before old one played through

### ISSUE THREAD

**Issue by woepaul** [MEGA65/mega65-rom-public#3]
Using the PLAY command causes issues if you send a new sequence to the same SID before the old sequence fully played through. To improve the practical value of PLAY it would be great if it could gracefully handle getting new requests for a SID before the previous sequence completed. 

The preferred behavior should be to cancel the ongoing sequence and replace it with the new one

Alternatively there could be a way to detect if a SID is still playing so that a basic program could decide when to send a new sequence. The drawback would be that this does not provide the ability to cancel a running sequence and immediately play something else on the same SID.

**Comment by gurcei** [comment]
Agree that there are a few edge-case behaviours that occasionally play-up with PLAY.

The case you describe sounds familiar to me. I think it happens some of the time, not all of the time, and I didn't get a good chance to debug it yet as it was hard to replicate during a debugging session.

I recall a similar error in the past which we fixed by assuring that new PLAY calls did their preparation work with interrupts disabled, and re-enabling once they were done.

That solved the prior problem, but seems like there's another edge-case like this to hunt down.

My free time is more limited this year, so if you or anyone else wants to give debugging the matter a try, happy to walk you through the section of the source involved and share any insights on it.

I believe the closed-rom source is available to all mega65 owners upon request, it can be compiled with Bitshifter's BSA compiler, and if you want to debug along with the original source (rather than raw disassembly), the m65dbg debugger supports reading in symbol information from BSA's .list files.

**Comment by gurcei** [comment]
Oh, one aspect of your q I missed was if there was a way to detect when a SID channel has finished playing a sequence?

Yes there is, you can use the RPLAY(channel) command to assess is a melody has finished playing on a channel.

**Comment by woepaul** [comment]
I provided steps how to reproduced the issue in:
https://discord.com/channels/719326990221574164/795760112425369610/980041514434580490

**Comment by dansanderson** [comment]
I am able to reproduce this with the latest ROM and core, so I'm reclassifying it as a bug. The test procedure mentioned is to use the `"PLAY EXAMPLE"` program from `BASIC65.D81`, which plays a recurring sequence in one voice and offers keyboard triggers for two other voices. Triggering the sequences quickly and haphazardly can put the music system in a broken state for those voices.

**Comment by dansanderson** [comment]
I messed with this some tonight and am convinced that this is a core issue. I'm consolidating this with: https://github.com/MEGA65/mega65-core/issues/573
