### ISSUE TITLE
Syntax error when FOR initial value expression is an array element

### ISSUE THREAD

**Issue by dansanderson** [MEGA65/mega65-rom-public#31]
**Test Environment (required)**
You can use [MEGA65INFO](https://files.mega65.org?id=3eeb7d82-8bd7-44b7-82b6-cef29d123b0e) to retrieve this.
 - Platform: MEGA65
 - ROM Release: 920377
 - Core Commit: 2f545d1

**Describe the bug**
When the initial value expression of a FOR statement is an array element, BASIC 65 throws a syntax error.

**To Reproduce**
```
10 DIM AB(10)
20 AB(0)=5
30 FOR X=AB(0) TO 10
40 PRINT X
50 NEXT
```

**Expected behavior**
Example should count from 5 to 10. Instead, it's a syntax error on line 30.

**Additional context**

* The breakage begins at ROM 920279.
* Same result for single-letter (fast) or double-letter array name
* Same result if the array reference is part of an expression: `(AB(0))`, or `3*AB(0)`, or `AB(0)*3`
* Same result regardless of the index
* Same result for integer array vs. number array: `A%(0)`
* Does not happen if the array reference is only in the final value expression: `FOR X=1 TO AB(0)`

**Comment by fredrikr** [comment]
FOR calls LET to assign the start value to the index variable. Before doing this, it sets two flags: Don't allow byte variables and don't allow array variables. It makes sense to put these restrictions in place for the left-hand side of the assignment, but not the right-hand side of it.

Either:

Solution A: Assume that it's never desirable to have variable type restrictions in place when evaluating the right-hand side of a variable assignment. Clear all such flags just after the initial `jsr ptrvar` in LET.

or

Solution B: Let it be the responsibility of FOR, which enabled the variable type restriction flags, to disable them again. To do this in the FOR code, instead of `jsr let`, do:
```
    jsr ptrvar
    rmb7 subflg      ;enable subscripts
    rmb5 subflg      ;enable byte variable
    jsr [new label in LET, just after the initial jsr ptrvar]
``` 

(Note: I haven't tested any of this)

**Comment by dansanderson** [comment]
Solution B works. Am running it through more tests now, will accept if I can't find issues.
