### ISSUE TITLE
RENUMBER fails if range argument includes multiple lines and doesn't start on first line

### ISSUE THREAD

**Issue by fredrikr** [MEGA65/mega65-rom-public#32]
**Test Environment (required)**
You can use [MEGA65INFO](https://files.mega65.org?id=3eeb7d82-8bd7-44b7-82b6-cef29d123b0e) to retrieve this.
 - Platform: MEGA65
 - ROM Release: 920377
 - Core Commit: 93d55f0

**Describe the bug**
If you issue the renumber command and supply the range argument, and this range of line number holds more than one line and the first line in the range isn't the first line of the program, you often get a Can't continue error.

**To Reproduce**
Enter this:

10 print 1
20 print 2
30 print 3
40 print 4

renumber 100,10,20

or:

renumber 100,10,20-30

However, this works:

renumber 100,10,15

**Expected behavior**
The lines I asked to be renumbered should be renumbered, and no error should occur.

**Additional context**
I haven't yet managed to pin down exactly which conditions make it fail.

**Comment by dansanderson** [comment]
I believe the general issue is that RENUMBER, as it is currently implemented, will never reorder lines. `RENUMBER 1,1,40` also fails in the above example. `RENUMBER 100,1,40` succeeds.

It would be useful to be able to move regions of the program around, but it's not obvious how this should be implemented. Any renumbering that would cause the renumbered lines to overlap or interleave probably produces an unwanted result. Maybe explicitly disallowing those cases is sufficient for usability: the renumber could succeed if all lines in the range would stay contiguous in the renumbering. (I don't know what this would cost in ROM code bytes to implement, but it's a reasonable design otherwise.)

We recently discussed in the Discord what a workaround might look like. Listing a line range to a SEQ file, deleting the line range, RENUMBERing, and IMPORTing the SEQ file later is a plausible albeit cumbersome technique. MERGE also has some limited functionality with PRG files.

**Comment by fredrikr** [comment]
I was convinced I had this fail with renumber commands that wouldn't move the lines, but I can't reproduce it now. I probably just made a mistake.

Here's a scenario which isn't working properly though. Sorry about the image quality.

![20230221_134706](https://user-images.githubusercontent.com/1001548/220349204-54a0cc6a-098b-4114-a687-e3fca22930fa.jpg)

Specifying a range that starts with "-" seems to work fine, but not one that ends with "-".

**Comment by fredrikr** [comment]
This seems to need an issue of its own, or it'll be forgotten. I created https://github.com/MEGA65/mega65-rom-public/issues/57 so we can close this.
