### ISSUE TITLE
Saving a program > free disk space makes M65 crash

### ISSUE THREAD

**Issue by Schwefelholz** [MEGA65/mega65-rom-public#33]
**Test Environment (required)**
You can use [MEGA65INFO](https://files.mega65.org/?id=3eeb7d82-8bd7-44b7-82b6-cef29d123b0e) to retrieve this.

    Platform: MEGA65
    ROM Release: 920377
    Core Commit: 93d55f0

**Describe the bug**
Trying to save a program (save or dsave) which requires more space on disk than is available, makes the system crash/hang and leaves a non-closed file on the disk.

**To Reproduce**
- Attach mega65.d81 floppy image (131 blocks of free space).
- Load autoboot.c65 resp. menu (148 blocks).
- Use save or dsave to save with a different name (e.g. save "test")

**Expected behavior**
save/dsave should fail with an error message and give control back to the kernal.

**Additional context**
I have tried this with two floppy images, but not with a physical disk.

**Comment by Schwefelholz** [comment]
save in the C64 subsystem behaves the same way.

**Comment by Schwefelholz** [comment]
A physical disk also behaves the same way.

**Comment by johnwayner** [comment]
I've found the bug causing the DOS to get in an infinite loop when the disk is full.  And I have a pretty good idea why the file is not closed properly.  But I do wonder what the right behavior should be in this case. Perhaps it's better to leave the partially saved file unclosed as an indication that it's probably useless anyway.

I'm inclined to leave the file improperly closed as the change to make that not the case would likely be more invasive, and it's not clear it's even the right behavior.  Please comment here if you disagree.  Meanwhile, I'll submit the fix for the lock up.

**Comment by Schwefelholz** [comment]
> I've found the bug causing the DOS to get in an infinite loop when the disk is full. And I have a pretty good idea why the file is not closed properly. But I do wonder what the right behavior should be in this case. Perhaps it's better to leave the partially saved file unclosed as an indication that it's probably useless anyway.
> 
> I'm inclined to leave the file improperly closed as the change to make that not the case would likely be more invasive, and it's not clear it's even the right behavior. Please comment here if you disagree. Meanwhile, I'll submit the fix for the lock up.

Makes sense as this actually is the behavior on a C64: The file is kept unclosed, control is passed back to the KERNAL and there is a 72 - Disk Full error message on the disk drive.
