### ISSUE TITLE
SLEEP command breaks after 72 minutes

### ISSUE THREAD

**Issue by fredrikr** [MEGA65/mega65-rom-public#37]
**Test Environment (required)**
You can use [MEGA65INFO](https://files.mega65.org?id=3eeb7d82-8bd7-44b7-82b6-cef29d123b0e) to retrieve this.
 - Platform: MEGA65
 - ROM Release: 920377
 - Core Commit: 93d55f0

**Describe the bug**
If the CIA timers used for the SLEEP command are about to wrap, and you issue a SLEEP command that would extend beyond the wrap time, the SLEEP command never ends. This normally happens ~72 minutes after the computer was started. This is because the 32-bit timer at $dd04 (actually two timers working together, timer A and timer B) wrap after 2^32 microseconds, or ~4300 seconds. (I found this by reading the source code of the ROM)

**To Reproduce**
Run this:

10 print int(ti)
20 sleep 10
30 goto 10

If you run this when the computer starts, it will keep printing a number every ten seconds, until it reaches ~4300. Then it stops. 

**Expected behavior**
SLEEP should finish normally after the number of seconds specified.

**Screenshots**
--

**Additional context**

**Comment by dansanderson** [comment]
Current algorithm:
1) Read argument.
2) Read time.
3) Add argument to time, store as target time.
4) Loop: Check time. End when current time > target time.

This fails in the edge case where current time overflows before the comparison, causing it to be < target time for another 72 minutes (max 32-bit microseconds).

Hopefully improved algorithm:
1) Read argument. Store argument.
2) Read time. Store as start time.
3) Loop: Check time, subtract start time. End when delta > argument.

This should survive the overflow because an overflowed subtraction should still be accurate. However, this assumption might be false with the kernel's floating point math subsystem. I have a non-working version of this and spent a couple of days trying to debug, but it's slow going. Pasting this here and setting it aside for the moment:

```
    ; tempf1: start time
    ; tempf2: requested duration
    jsr frmnum      ; FAC = wait time argument
    ldx #tempf2
    jsr factorx     ; tempf2 = FAC
    jsr Get_TI_CIA  ; FAC = current time
    jsr mov1f       ; tempf1 = FAC

10$ jsr is_stop_key_down   ; Allow user to abort
    jsr Get_TI_CIA  ; FAC = current time
    lda #<tempf1
    ldx #>tempf1    ; (FAC := duration since start)
    jsr fsub        ; FAC -= tempf1
    lda #<tempf2
    ldy #>tempf2
    jsr fcomp
    bmi 10$         ; if FAC < tempf2 then continue
    rts
```
