### ISSUE TITLE
TYPE lacks a paging option (as LIST has got one)

### ISSUE THREAD

**Issue by Schwefelholz** [MEGA65/mega65-rom-public#47]
**Is your feature request related to a problem? Please describe.**
Using TYPE to view a file longer than 25 lines will have the first lines scroll off the screen, so one cannot read them.

**Describe the solution you'd like**
TYPE should implement a paging mechanism as is implemented for LIST (LIST P "filename").

**Describe alternatives you've considered**
none.

**Additional context**
none

**Comment by Schwefelholz** [comment]
Thinking about it, the paging mechanism should be default for TYPE. It makes no sense at all having TYPE without it.

**Comment by dansanderson** [comment]
I would want it to be an option so that the default behavior is to send the file to the output channel, because this channel can be redirected, e.g. to a printer. It should be consistent with DIR and LIST in this respect.

I acknowledge that redirecting the output is a minority use case, but it's a design tenet of Commodore BASIC and other terminal-style APIs of the era to do the simple terminal output thing by default, to make it easier to understand interactively what redirecting the output would do. This makes more sense in Unix with the shell piping feature, but it still makes some sense in the Commodore case.

FWIW I have a personal use case for TYPE that uses PETSCII control codes to manage screen output. It's not obvious what the paging feature should do when the file contains such codes. I'll look at the paging features of the other commands and see if there's a way to standardize the behavior (e.g. to pause only on a "screen scroll," vs. a fixed number of newlines).

**Comment by Schwefelholz** [comment]
Agreed. There might be use cases where paging might be undesired.

**Comment by dansanderson** [comment]
Implemented. https://github.com/MEGA65/mega65-rom/commit/4fb072f08c01881536a4b7135097edaa838e6d9a
