### ISSUE TITLE
DISK does not correctly pass on commands starting with a slash (/)

### ISSUE THREAD

**Issue by Schwefelholz** [MEGA65/mega65-rom-public#48]
**Test Environment (required)**
You can use [MEGA65INFO](https://files.mega65.org?id=3eeb7d82-8bd7-44b7-82b6-cef29d123b0e) to retrieve this.
 - Platform: MEGA65 R3
 - ROM Release: 920377
 - Core Commit: 93d55r0

**Describe the bug**
Creating or changing into a partition/subdir on an IEC drive/on a 1581 requires to send disk commands with a leading slash. DISK will make the drive throw a `31,SYNTAX ERROR,00,00`, while using OPEN/PRINT# statements with the same command string are working fine.

**To Reproduce**
1. Unit 11 is a 1581 with a plain formatted disk inserted
2.  send `DISK"/0:SUBDIR,"+CHR$(1)+CHR$(0)+CHR$(200)+CHR$(0)+",C",U11` to create a partition 
3. Result: `UNIT:11 31,SYNTAX ERROR,00,00`

or less complex:
1. Unit 11 is a 1581 with a formatted disk containing a partition/subdirectory SUBDIR
2. send `DISK"/0:SUBDIR",U11` to change into SUBDIR
3. Result: `UNIT:11 31,SYNTAX ERROR,00,00`

Changing back to root:
1. Unit 11 is a 1581 with a formatted disk containing a partition/subdirectory SUBDIR. We are currently in the subdirectory
2. send `DISK"/",U11` to change back to the root directory 
3. Result: We receive a `READY.` prompt, but actually did not change the directory (refer to `DIR U11`)

**Expected behavior**
Example 1 should create a partition on the disk as correctly does
`OPEN 1,11,15,"/0:SUBDIR,"+CHR$(1)+CHR$(0)+CHR$(200)+CHR$(0)+",C" : CLOSE 1`

Example 2 should change into partition/subdirectory SUBDIR as correctly does
`OPEN 1,11,15,"/0:SUBDIR" : CLOSE 1`

Example 3 should change back to the disk's root directory as correctly does
`OPEN 1,11,15,"/" : CLOSE 1`

**Comment by dansanderson** [comment]
Going just from code review, it looks like the `DISK` command is reusing logic intended for handling filename strings for other commands as a way to pass through the command string. It is possible that treating the command string as a filename is causing it to get corrupted slightly on its way out. As far as I can tell, the `DISK` command would be better off sending the raw command string without any processing. There are code comments that suggest the current behavior is intentional, but I don't understand why just from looking at the code and at 1581 documentation.

Internal details: The `DISK` command uses the `fdisk` entry in the `tabld` table to form the final disk command, using the `sendp` tokens `xfat,xfn1`. Going just from code review, `xfat` appears to insert a leading `@` or `/` under certain circumstances, and `xfn1` copies in the string but ignores a leading `/` (presumably because it assumes `xfat` is taking care of it). Comments indicate that the `disk:` command is intentionally trying to add a leading `/` character, but again maybe just because `xfn1` eats the leading slash. It's possible that the fix would be for `DISK` to use separate logic to copy the command string directly into `dosstr`, or something like that.

I have a 1581 to test with but it's not set up at the moment. I'll look into it when I get a chance.

P.S. My recollection is partitions are not supported for the internal 3-1/2" floppy drive. `DISK` is a new command in BASIC 65, so this probably didn't get enough testing.

**Comment by Schwefelholz** [comment]
Actually, the internal 3.5" drives do support partitions, but the commands to create/make use of them differ from the way the 1581 is using.
The internal drives simply use the `MKDIR`/`CHDIR` commands. The effect is the same as with the more complicated disk commands used on the 1581.

**Comment by Schwefelholz** [comment]
Learned that the hard way, as well... ;-)
