### ISSUE TITLE
DSAVE returns "Illegal Filename Syntax" when trying to save a file with the character "#" in it.

### ISSUE THREAD

**Issue by MauriceMEGA65** [MEGA65/mega65-rom-public#60]
**Test Environment (required)**
You can use [MEGA65INFO](https://files.mega65.org?id=3eeb7d82-8bd7-44b7-82b6-cef29d123b0e) to retrieve this.
 - Platform: MEGA65, XEMU
 - ROM Release: 920377
 - Core Commit: Batch2

**Describe the bug**
DSAVE returns "Illegal Filename Syntax" when trying to save a file with the character "#" in it.

**To Reproduce**
1. Create or open a BASIC program
2. Save it, use a "#" in the filename. For instance DSAVE "TEST#"

**Expected behavior**
Program saved, with filename "TEST#"

**Screenshots**
See screenshot
![IMG_4291](https://github.com/MEGA65/mega65-rom-public/assets/75681098/b3d3ac57-1cce-49b4-9b81-a98698769442)

**Additional context**
Works fine on batch1 ROM like 920287

**Comment by dansanderson** [comment]
Apologies for the delay looking at this. This change was intentional: it added more pattern matching syntax, and disallows adding pattern matching characters to filenames when saving. `#` matches a digit, `$` matches a letter, `?` matches a single of any character, `*` matches any number of any character.

https://github.com/MEGA65/mega65-rom/commit/f07545ebddeecd35596bde42cc1126b8987c3672

Please reopen the issue if there's a pressing need to include these characters in filenames when saving. We're unlikely to roll back the feature that was added.

**Comment by MauriceMEGA65** [comment]
Hmmm.... since all patterns can be covered by **?** and *****, it seems redundant to me to also use **#** and **$**.
No man overboard, but I did use # quite frequently on the BASIC65.D81, not sure if it will come to a surprise to users if they are not able to save their files in the same way as on the D81.

**Comment by dansanderson** [comment]
I'm not particularly fond of the feature either to be honest. I'm trying to take a general position not to roll back any of Bit Shifter's additions unless they're causing serious problems. I do see what you mean with BASIC65.D81.🤷‍♂️
