### ISSUE TITLE
SPRITE messes up TI$

### ISSUE THREAD

**Issue by dansanderson** [MEGA65/mega65-rom-public#83]
**Test Environment (required)**
You can use [MEGA65INFO](https://files.mega65.org?id=3eeb7d82-8bd7-44b7-82b6-cef29d123b0e) to retrieve this.
 - Platform: MEGA65, xemu
 - ROM Release: 920387
 - Core Commit: dea350f

**Describe the bug**
`SPRITE 2,1,5` messes up `TI$`. It stops advancing, and gets messed up by disk activity.

**To Reproduce**
```
?TI$
?TI$
SPRITE 2,1,5
?TI$
?TI$
DSAVE "TEST"
?TI$
```

**Comment by snoopy-f64** [comment]
The trace led me in b65.src to the routines that generate TI$. I have no idea why it was done this way, but it reads in the address $D029 (Sprite 2 colour), it got the name "megarev" to check a revision of the board. And if the address content is greater than 4, the routines are exited.

I really have no idea why someone read in the sprite 2 colour to find out a revision? If you assign a colour greater than 4 to sprite 2, TI$ just goes crazy. But because of the colour of the sprite and not because of a board revision.

![mega65_tistr_d](https://github.com/MEGA65/mega65-rom-public/assets/66867430/507c8e53-838c-4952-8ce1-f9bc8b7ec7c4)

![mega65_tistr_e](https://github.com/MEGA65/mega65-rom-public/assets/66867430/f393f4f4-3c4e-4237-8dae-ae585c5d8617)

![mega65_tistr_f](https://github.com/MEGA65/mega65-rom-public/assets/66867430/8de427d1-e9f6-4962-bc17-480ddc6b9999)

This error took me all day yesterday to troubleshoot. I suspected and searched for the error somewhere in my code. You first have to come up with the idea that the colour of sprite 2 is the reason for an incorrect TI$ in ROM. Crazy! :-)

**Comment by dansanderson** [comment]
Wow. This should be $d629. Fixed and tested.

Thanks so much for tracking this down!
