### ISSUE TITLE
New key scanner: MegaAssembler and Coffeebreak are getting 0's from GETKEY

### ISSUE THREAD

**Issue by dansanderson** [MEGA65/mega65-rom-public#86]
**Test Environment (required)**
You can use [MEGA65INFO](https://files.mega65.org?id=3eeb7d82-8bd7-44b7-82b6-cef29d123b0e) to retrieve this.
 - Platform: MEGA65
 - ROM Release: 920388
 - Core Commit: development,20231010.19,88f067d

**Describe the bug**
With the new keyboard scanner core and ROM, typing in MegaAssembler and Coffeebreak is not working. The cursor blinks on key events, but does not actually type.

MegaAssembler 2.03 uses GETKEY for reading key presses (and CURSOR ON to blink the cursor). A short test program with GETKEY does not have an issue. If I add code after line 1040 to display the value of K$/K, it shows it is getting set to 0. This should only happen when typing Ctrl-@. A short test program printing results from GETKEY does not have an issue, so there must be some kind of corner case that GETKEY or `getin` isn't handling.

Eleven is not having this issue, though someone reported it was behaving similarly. I wonder if the corner case can be tripped by the user as well as the prorgam. I definitely tested Eleven, MA, and TCC when I was developing the keyboard scanner, so I didn't find it then. It's easy to reproduce in MA and TCC now.

I thought maybe `CURSOR ON` could be related, but so far I haven't been able to repro the issue with that involved.

**Comment by rscottfree** [comment]
It might be `KEY OFF` that is the problem. Typing that in direct mode appears to lock up the computer (although it's probably just blocking keyboard input). Using it in a basic program breaks user input, including `INPUT` and `GET` statements, but otherwise the program will continue executing. Both MA and TCC use `KEY OFF`. Running `KEY ON` restores the ability to get keyboard input unless you're stuck in a `GET` loop or waiting for `INPUT`.

**Comment by dansanderson** [comment]
Thanks very much! This is now fixed in ROM 920389.
